# Name of workflow
name: action_tests

# Trigger the workflow on push or pull request
on:
  - push
  - pull_request

env:
  CI: true

jobs:
  build:

    # The type of machine to run the job on
    runs-on: ubuntu-latest

    strategy:
      # Node versions list
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: npm install
        run:
          make install
        env:
          CI: true
      - name: Run linter
        run:
          make lint
      - name: Run Test
        run:
          make test
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v2.7.4
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage
          debug: true
